### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5736bc66ae12466c99d1bb51cc13b12c",
  "accountNumber": "1000000001",
  "amount": 12345
}

### query transaction
GET http://localhost:8080/transaction/0169d8fa14134a98a41738011a74ad2a